import Head from 'next/head'
import { Inter } from '@next/font/google'
import Image from 'next/image'
import Wrapper from './components/wrapper'
import NewsEvent from './components/Sections/NewsEvent'
// import Footer from './components/Layout/Footer'
// import Navbar from './components/Layout/Navbar'
import Services from './components/Sections/Services'
import Information from './components/Sections/Information'
import Contact from './components/Sections/Contact'


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>For students | Univesity of Stuttgart</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Wrapper>
        {/* <Navbar /> */}
        <div className='bg-[#00beff] sm:flex-col flex justify-between sm:px-4 px-[5.625rem] pt-10 pb-20 gap-x-10'>
          <div className='flex flex-col gap-y-5'>
            <h1 className='font-bold text-2xl'>Students</h1>
            <p className='text-lg'>Important news, links, documents, and tips for students of the University of Stuttgart: This page offers information on your studies.</p>
          </div>
          <div className='sm:-mb-0 -mb-24'>
            <button className='sm:flex hidden gap-3 items-center mt-6'>
              <span className='group-hover:stroke-black'>
                <svg xmlns="http://www.w3.org/2000/svg" fill="#000000" width="20px" height="20px" viewBox="0 0 20 20"><path d="M12.95 10.707l.707-.707L8 4.343 6.586 5.757 10.828 10l-4.242 4.243L8 15.657l4.95-4.95z" /></svg>
              </span>
              <span className='hover:no-underline underline font-bold text-base'>INFORMATION FOR PROSPECTIVE STUDENTS</span>
            </button>
            <button className='sm:hidden bg-black group w-64 h-64 rounded-full flex flex-col  items-center justify-between p-10  hover:bg-white text-white hover:text-black'>
              <span className='font-bold text-base mt-5 p-3'>INFORMATION FOR PROSPECTIVE STUDENTS</span>
              <span className='group-hover:stroke-black'>
                <svg xmlns="http://www.w3.org/2000/svg" fill="#ffffff" width="20px" height="20px" viewBox="0 0 20 20"><path d="M12.95 10.707l.707-.707L8 4.343 6.586 5.757 10.828 10l-4.242 4.243L8 15.657l4.95-4.95z" /></svg>
              </span>
            </button>
          </div>
        </div>
        <div className='bg-white pt-14 pb-8'>
          <div className='bg-[#eeeeee] py-5 flex flex-col gap-y-5 px-10 sm:mx-3 mx-48'>
            <label className='text-gray-600'>Begriff</label>
            <input type="text" placeholder='Suchen Sie nach Begriffen aus dem Uni-Glossar' className='bg-white border p-4 border-[#eeeeee] outline-none w-full' />
            <button className='bg-[#004191] w-52 text-white hover:bg-gray-900 outline-none py-2 px-4'>Begriff suchen</button>
          </div>
        </div>
        <Services />
        <NewsEvent />
        <Information />
        <Contact />
        {/* <Footer /> */}
      </Wrapper>
    </>
  )
}
